"""One-time script: add the auth illustration/benefit/quote keys to all locales."""
import json
import os

BASE = os.path.join(os.path.dirname(__file__), '..', 'frontend', 'src', 'i18n', 'locales')

# Keys: illustrationTitle1/2, benefit*, quoteText/Author, reg* (register equivalents)
AUTH_KEYS = {
    'en': {
        'illustrationTitle1': 'Continue building',
        'illustrationTitle2': 'amazing forms',
        'benefitAccess': 'Access your forms and responses',
        'benefitRules': 'Manage conditional rules',
        'benefitAnalytics': 'View analytics and insights',
        'benefitSecure': 'Secure, encrypted access',
        'quoteText': 'The best form builder we have ever used.',
        'quoteAuthor': '\u2014 TechFlow Team',
        'regIllustrationTitle1': 'Start building',
        'regIllustrationTitle2': 'dynamic forms today',
        'regBenefitFree': 'Free account \u2014 no credit card needed',
        'regBenefitBuilder': 'Drag-and-drop form builder',
        'regBenefitLogic': 'Powerful conditional logic',
        'regBenefitShare': 'Share forms with a single link',
        'regQuoteText': 'Went from zero to fully functional forms in under 10 minutes.',
        'regQuoteAuthor': '\u2014 Sarah Chen, PM',
    },
    'hi': {
        'illustrationTitle1': 'जारी रखें बनाना',
        'illustrationTitle2': 'अद्भुत फॉर्म',
        'benefitAccess': 'अपने फॉर्म और प्रतिक्रियाएँ एक्सेस करें',
        'benefitRules': 'कंडीशनल नियम प्रबंधित करें',
        'benefitAnalytics': 'एनालिटिक्स और इनसाइट्स देखें',
        'benefitSecure': 'सुरक्षित, एन्क्रिप्टेड एक्सेस',
        'quoteText': 'सबसे अच्छा फॉर्म बिल्डर जो हमने कभी इस्तेमाल किया है।',
        'quoteAuthor': '\u2014 TechFlow टीम',
        'regIllustrationTitle1': 'शुरू करें बनाना',
        'regIllustrationTitle2': 'आज ही डायनामिक फॉर्म',
        'regBenefitFree': 'मुफ्त खाता \u2014 क्रेडिट कार्ड की जरूरत नहीं',
        'regBenefitBuilder': 'ड्रैग-एंड-ड्रॉप फॉर्म बिल्डर',
        'regBenefitLogic': 'शक्तिशाली कंडीशनल लॉजिक',
        'regBenefitShare': 'एक लिंक से फॉर्म शेयर करें',
        'regQuoteText': '10 मिनट से भी कम समय में शून्य से पूर्ण कार्यात्मक फॉर्म तक।',
        'regQuoteAuthor': '\u2014 सारा चेन, PM',
    },
    'te': {
        'illustrationTitle1': 'నిర్మాణం కొనసాగించండి',
        'illustrationTitle2': 'అద్భుతమైన ఫారాలు',
        'benefitAccess': 'మీ ఫారాలు మరియు ప్రతిస్పందనలను యాక్సెస్ చేయండి',
        'benefitRules': 'కండీషనల్ నియమాలను నిర్వహించండి',
        'benefitAnalytics': 'విశ్లేషణలు మరియు అంతర్దృష్టులను చూడండి',
        'benefitSecure': 'సురక్షితమైన, ఎన్‌క్రిప్టెడ్ యాక్సెస్',
        'quoteText': 'మేము ఉపయోగించిన ఉత్తమ ఫారం బిల్డర్.',
        'quoteAuthor': '\u2014 TechFlow టీమ్',
        'regIllustrationTitle1': 'నిర్మాణం ప్రారంభించండి',
        'regIllustrationTitle2': 'ఈ రోజే డైనమిక్ ఫారాలు',
        'regBenefitFree': 'ఉచిత ఖాతా \u2014 క్రెడిట్ కార్డ్ అవసరం లేదు',
        'regBenefitBuilder': 'డ్రాగ్-అండ్-డ్రాప్ ఫారం బిల్డర్',
        'regBenefitLogic': 'శక్తివంతమైన కండీషనల్ లాజిక్',
        'regBenefitShare': 'ఒక లింక్‌తో ఫారాలను భాగస్వామ్యం చేయండి',
        'regQuoteText': '10 నిమిషాలలోపు సున్నా నుండి పూర్తి ఫంక్షనల్ ఫారాలు వరకు.',
        'regQuoteAuthor': '\u2014 సారా చెన్, PM',
    },
    'ta': {
        'illustrationTitle1': 'தொடர்ந்து உருவாக்குங்கள்',
        'illustrationTitle2': 'அற்புதமான ஃபார்ம்கள்',
        'benefitAccess': 'உங்கள் ஃபார்ம்கள் மற்றும் பதில்களை அணுகவும்',
        'benefitRules': 'நிபந்தனை விதிகளை நிர்வகிக்கவும்',
        'benefitAnalytics': 'பகுப்பாய்வு மற்றும் நுண்ணறிவுகளைப் பார்க்கவும்',
        'benefitSecure': 'பாதுகாப்பான, குறியாக்கப்பட்ட அணுகல்',
        'quoteText': 'நாங்கள் பயன்படுத்திய சிறந்த ஃபார்ம் பில்டர்.',
        'quoteAuthor': '\u2014 TechFlow குழு',
        'regIllustrationTitle1': 'உருவாக்கத் தொடங்குங்கள்',
        'regIllustrationTitle2': 'இன்றே டைனமிக் ஃபார்ம்கள்',
        'regBenefitFree': 'இலவச கணக்கு \u2014 கிரெடிட் கார்டு தேவையில்லை',
        'regBenefitBuilder': 'ட்ராக்-அண்ட்-ட்ராப் ஃபார்ம் பில்டர்',
        'regBenefitLogic': 'சக்திவாய்ந்த நிபந்தனை தர்க்கம்',
        'regBenefitShare': 'ஒரே இணைப்பில் ஃபார்ம்களைப் பகிருங்கள்',
        'regQuoteText': '10 நிமிடங்களுக்குள் பூஜ்ஜியத்திலிருந்து முழு செயல்பாட்டு ஃபார்ம்கள் வரை.',
        'regQuoteAuthor': '\u2014 சாரா சென், PM',
    },
    'kn': {
        'illustrationTitle1': 'ನಿರ್ಮಾಣ ಮುಂದುವರಿಸಿ',
        'illustrationTitle2': 'ಅದ್ಭುತ ಫಾರ್ಮ್‌ಗಳು',
        'benefitAccess': 'ನಿಮ್ಮ ಫಾರ್ಮ್‌ಗಳು ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆಗಳನ್ನು ಪ್ರವೇಶಿಸಿ',
        'benefitRules': 'ಷರತ್ತುಬದ್ಧ ನಿಯಮಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
        'benefitAnalytics': 'ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಒಳನೋಟಗಳನ್ನು ನೋಡಿ',
        'benefitSecure': 'ಸುರಕ್ಷಿತ, ಎನ್‌ಕ್ರಿಪ್ಟೆಡ್ ಪ್ರವೇಶ',
        'quoteText': 'ನಾವು ಬಳಸಿದ ಅತ್ಯುತ್ತಮ ಫಾರ್ಮ್ ಬಿಲ್ಡರ್.',
        'quoteAuthor': '\u2014 TechFlow ತಂಡ',
        'regIllustrationTitle1': 'ನಿರ್ಮಾಣ ಪ್ರಾರಂಭಿಸಿ',
        'regIllustrationTitle2': 'ಇಂದೇ ಡೈನಾಮಿಕ್ ಫಾರ್ಮ್‌ಗಳು',
        'regBenefitFree': 'ಉಚಿತ ಖಾತೆ \u2014 ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್ ಅಗತ್ಯವಿಲ್ಲ',
        'regBenefitBuilder': 'ಡ್ರ್ಯಾಗ್-ಅಂಡ್-ಡ್ರಾಪ್ ಫಾರ್ಮ್ ಬಿಲ್ಡರ್',
        'regBenefitLogic': 'ಶಕ್ತಿಯುತ ಷರತ್ತುಬದ್ಧ ತರ್ಕ',
        'regBenefitShare': 'ಒಂದು ಲಿಂಕ್‌ನೊಂದಿಗೆ ಫಾರ್ಮ್‌ಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
        'regQuoteText': '10 ನಿಮಿಷಗಳಲ್ಲಿ ಶೂನ್ಯದಿಂದ ಸಂಪೂರ್ಣ ಕಾರ್ಯನಿರ್ವಹಣೆಯ ಫಾರ್ಮ್‌ಗಳಿಗೆ.',
        'regQuoteAuthor': '\u2014 ಸಾರಾ ಚೆನ್, PM',
    },
    'ml': {
        'illustrationTitle1': 'നിർമ്മാണം തുടരുക',
        'illustrationTitle2': 'അത്ഭുതകരമായ ഫോമുകൾ',
        'benefitAccess': 'നിങ്ങളുടെ ഫോമുകളും പ്രതികരണങ്ങളും ആക്സസ് ചെയ്യുക',
        'benefitRules': 'കണ്ടീഷണൽ നിയമങ്ങൾ കൈകാര്യം ചെയ്യുക',
        'benefitAnalytics': 'വിശകലനങ്ങളും ഉൾക്കാഴ്ചകളും കാണുക',
        'benefitSecure': 'സുരക്ഷിതമായ, എൻക്രിപ്റ്റ് ചെയ്ത ആക്സസ്',
        'quoteText': 'ഞങ്ങൾ ഉപയോഗിച്ച ഏറ്റവും മികച്ച ഫോം ബിൽഡർ.',
        'quoteAuthor': '\u2014 TechFlow ടീം',
        'regIllustrationTitle1': 'നിർമ്മാണം ആരംഭിക്കുക',
        'regIllustrationTitle2': 'ഇന്നുതന്നെ ഡൈനാമിക് ഫോമുകൾ',
        'regBenefitFree': 'സൗജന്യ അക്കൗണ്ട് \u2014 ക്രെഡിറ്റ് കാർഡ് ആവശ്യമില്ല',
        'regBenefitBuilder': 'ഡ്രാഗ്-ആൻഡ്-ഡ്രോപ്പ് ഫോം ബിൽഡർ',
        'regBenefitLogic': 'ശക്തമായ കണ്ടീഷണൽ ലോജിക്',
        'regBenefitShare': 'ഒരു ലിങ്കിലൂടെ ഫോമുകൾ പങ്കിടുക',
        'regQuoteText': '10 മിനിറ്റിനുള്ളിൽ പൂജ്യത്തിൽ നിന്ന് പൂർണ്ണ പ്രവർത്തനക്ഷമമായ ഫോമുകളിലേക്ക്.',
        'regQuoteAuthor': '\u2014 സാറ ചെൻ, PM',
    },
    'bn': {
        'illustrationTitle1': 'তৈরি করা চালিয়ে যান',
        'illustrationTitle2': 'চমৎকার ফর্ম',
        'benefitAccess': 'আপনার ফর্ম এবং প্রতিক্রিয়া অ্যাক্সেস করুন',
        'benefitRules': 'কন্ডিশনাল নিয়ম পরিচালনা করুন',
        'benefitAnalytics': 'বিশ্লেষণ এবং অন্তর্দৃষ্টি দেখুন',
        'benefitSecure': 'নিরাপদ, এনক্রিপ্টেড অ্যাক্সেস',
        'quoteText': 'সেরা ফর্ম বিল্ডার যা আমরা কখনও ব্যবহার করেছি।',
        'quoteAuthor': '\u2014 TechFlow টিম',
        'regIllustrationTitle1': 'তৈরি করা শুরু করুন',
        'regIllustrationTitle2': 'আজই ডায়নামিক ফর্ম',
        'regBenefitFree': 'ফ্রি অ্যাকাউন্ট \u2014 ক্রেডিট কার্ডের প্রয়োজন নেই',
        'regBenefitBuilder': 'ড্র্যাগ-অ্যান্ড-ড্রপ ফর্ম বিল্ডার',
        'regBenefitLogic': 'শক্তিশালী কন্ডিশনাল লজিক',
        'regBenefitShare': 'একটি লিংকে ফর্ম শেয়ার করুন',
        'regQuoteText': '১০ মিনিটেরও কম সময়ে শূন্য থেকে সম্পূর্ণ কার্যকর ফর্ম।',
        'regQuoteAuthor': '\u2014 সারা চেন, PM',
    },
    'mr': {
        'illustrationTitle1': 'निर्माण सुरू ठेवा',
        'illustrationTitle2': 'अप्रतिम फॉर्म',
        'benefitAccess': 'तुमचे फॉर्म आणि प्रतिसाद मिळवा',
        'benefitRules': 'कंडिशनल नियम व्यवस्थापित करा',
        'benefitAnalytics': 'विश्लेषण आणि अंतर्दृष्टी पहा',
        'benefitSecure': 'सुरक्षित, एन्क्रिप्टेड प्रवेश',
        'quoteText': 'आम्ही वापरलेला सर्वोत्तम फॉर्म बिल्डर.',
        'quoteAuthor': '\u2014 TechFlow टीम',
        'regIllustrationTitle1': 'निर्माण सुरू करा',
        'regIllustrationTitle2': 'आजच डायनॅमिक फॉर्म',
        'regBenefitFree': 'मोफत खाते \u2014 क्रेडिट कार्ड आवश्यक नाही',
        'regBenefitBuilder': 'ड्रॅग-अँड-ड्रॉप फॉर्म बिल्डर',
        'regBenefitLogic': 'शक्तिशाली कंडिशनल लॉजिक',
        'regBenefitShare': 'एका लिंकसह फॉर्म शेअर करा',
        'regQuoteText': '10 मिनिटांत शून्यापासून पूर्ण कार्यरत फॉर्मपर्यंत.',
        'regQuoteAuthor': '\u2014 सारा चेन, PM',
    },
    'gu': {
        'illustrationTitle1': 'નિર્માણ ચાલુ રાખો',
        'illustrationTitle2': 'અદ્ભુત ફોર્મ્સ',
        'benefitAccess': 'તમારા ફોર્મ્સ અને પ્રતિસાદો ઍક્સેસ કરો',
        'benefitRules': 'કન્ડિશનલ નિયમો મેનેજ કરો',
        'benefitAnalytics': 'એનાલિટિક્સ અને આંતરદૃષ્ટિ જુઓ',
        'benefitSecure': 'સુરક્ષિત, એન્ક્રિપ્ટેડ ઍક્સેસ',
        'quoteText': 'અમે ઉપયોગમાં લીધેલ શ્રેષ્ઠ ફોર્મ બિલ્ડર.',
        'quoteAuthor': '\u2014 TechFlow ટીમ',
        'regIllustrationTitle1': 'નિર્માણ શરૂ કરો',
        'regIllustrationTitle2': 'આજે જ ડાયનેમિક ફોર્મ્સ',
        'regBenefitFree': 'મફત એકાઉન્ટ \u2014 ક્રેડિટ કાર્ડની જરૂર નથી',
        'regBenefitBuilder': 'ડ્રેગ-એન્ડ-ડ્રોપ ફોર્મ બિલ્ડર',
        'regBenefitLogic': 'શક્તિશાળી કન્ડિશનલ લોજિક',
        'regBenefitShare': 'એક લિંક સાથે ફોર્મ્સ શેર કરો',
        'regQuoteText': '10 મિનિટમાં શૂન્યથી સંપૂર્ણ કાર્યરત ફોર્મ્સ સુધી.',
        'regQuoteAuthor': '\u2014 સારા ચેન, PM',
    },
    'pa': {
        'illustrationTitle1': 'ਉਸਾਰੀ ਜਾਰੀ ਰੱਖੋ',
        'illustrationTitle2': 'ਸ਼ਾਨਦਾਰ ਫਾਰਮ',
        'benefitAccess': 'ਆਪਣੇ ਫਾਰਮ ਅਤੇ ਜਵਾਬਾਂ ਤੱਕ ਪਹੁੰਚ ਕਰੋ',
        'benefitRules': 'ਕੰਡੀਸ਼ਨਲ ਨਿਯਮ ਪ੍ਰਬੰਧਿਤ ਕਰੋ',
        'benefitAnalytics': 'ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਸੂਝ ਦੇਖੋ',
        'benefitSecure': 'ਸੁਰੱਖਿਅਤ, ਐਨਕ੍ਰਿਪਟਡ ਪਹੁੰਚ',
        'quoteText': 'ਸਭ ਤੋਂ ਵਧੀਆ ਫਾਰਮ ਬਿਲਡਰ ਜੋ ਅਸੀਂ ਕਦੇ ਵਰਤਿਆ ਹੈ।',
        'quoteAuthor': '\u2014 TechFlow ਟੀਮ',
        'regIllustrationTitle1': 'ਉਸਾਰੀ ਸ਼ੁਰੂ ਕਰੋ',
        'regIllustrationTitle2': 'ਅੱਜ ਹੀ ਡਾਇਨਾਮਿਕ ਫਾਰਮ',
        'regBenefitFree': 'ਮੁਫ਼ਤ ਖਾਤਾ \u2014 ਕ੍ਰੈਡਿਟ ਕਾਰਡ ਦੀ ਲੋੜ ਨਹੀਂ',
        'regBenefitBuilder': 'ਡਰੈਗ-ਐਂਡ-ਡ੍ਰੌਪ ਫਾਰਮ ਬਿਲਡਰ',
        'regBenefitLogic': 'ਸ਼ਕਤੀਸ਼ਾਲੀ ਕੰਡੀਸ਼ਨਲ ਲਾਜ਼ਿਕ',
        'regBenefitShare': 'ਇੱਕ ਲਿੰਕ ਨਾਲ ਫਾਰਮ ਸਾਂਝੇ ਕਰੋ',
        'regQuoteText': '10 ਮਿੰਟਾਂ ਵਿੱਚ ਜ਼ੀਰੋ ਤੋਂ ਪੂਰੀ ਤਰ੍ਹਾਂ ਕਾਰਜਸ਼ੀਲ ਫਾਰਮਾਂ ਤੱਕ।',
        'regQuoteAuthor': '\u2014 ਸਾਰਾ ਚੇਨ, PM',
    },
    'ur': {
        'illustrationTitle1': 'تعمیر جاری رکھیں',
        'illustrationTitle2': 'شاندار فارم',
        'benefitAccess': 'اپنے فارم اور جوابات تک رسائی حاصل کریں',
        'benefitRules': 'مشروط قواعد منظم کریں',
        'benefitAnalytics': 'تجزیات اور بصیرت دیکھیں',
        'benefitSecure': 'محفوظ، خفیہ کردہ رسائی',
        'quoteText': 'بہترین فارم بلڈر جو ہم نے کبھی استعمال کیا ہے۔',
        'quoteAuthor': '\u2014 TechFlow ٹیم',
        'regIllustrationTitle1': 'تعمیر شروع کریں',
        'regIllustrationTitle2': 'آج ہی ڈائنامک فارم',
        'regBenefitFree': 'مفت اکاؤنٹ \u2014 کریڈٹ کارڈ کی ضرورت نہیں',
        'regBenefitBuilder': 'ڈریگ-اینڈ-ڈراپ فارم بلڈر',
        'regBenefitLogic': 'طاقتور مشروط منطق',
        'regBenefitShare': 'ایک لنک کے ساتھ فارم شیئر کریں',
        'regQuoteText': '10 منٹ میں صفر سے مکمل فعال فارم تک۔',
        'regQuoteAuthor': '\u2014 سارہ چن، PM',
    },
    'es': {
        'illustrationTitle1': 'Sigue creando',
        'illustrationTitle2': 'formularios increíbles',
        'benefitAccess': 'Accede a tus formularios y respuestas',
        'benefitRules': 'Gestiona reglas condicionales',
        'benefitAnalytics': 'Consulta análisis y estadísticas',
        'benefitSecure': 'Acceso seguro y cifrado',
        'quoteText': 'El mejor creador de formularios que hemos usado.',
        'quoteAuthor': '\u2014 Equipo TechFlow',
        'regIllustrationTitle1': 'Empieza a crear',
        'regIllustrationTitle2': 'formularios dinámicos hoy',
        'regBenefitFree': 'Cuenta gratuita \u2014 sin tarjeta de crédito',
        'regBenefitBuilder': 'Creador de formularios drag-and-drop',
        'regBenefitLogic': 'Lógica condicional potente',
        'regBenefitShare': 'Comparte formularios con un solo enlace',
        'regQuoteText': 'Pasamos de cero a formularios totalmente funcionales en menos de 10 minutos.',
        'regQuoteAuthor': '\u2014 Sarah Chen, PM',
    },
    'fr': {
        'illustrationTitle1': 'Continuez à créer',
        'illustrationTitle2': 'des formulaires exceptionnels',
        'benefitAccess': 'Accédez à vos formulaires et réponses',
        'benefitRules': 'Gérez les règles conditionnelles',
        'benefitAnalytics': 'Consultez les analyses et statistiques',
        'benefitSecure': 'Accès sécurisé et chiffré',
        'quoteText': 'Le meilleur créateur de formulaires que nous ayons utilisé.',
        'quoteAuthor': '\u2014 Équipe TechFlow',
        'regIllustrationTitle1': 'Commencez à créer',
        'regIllustrationTitle2': 'des formulaires dynamiques dès aujourd\'hui',
        'regBenefitFree': 'Compte gratuit \u2014 sans carte bancaire',
        'regBenefitBuilder': 'Créateur de formulaires glisser-déposer',
        'regBenefitLogic': 'Logique conditionnelle puissante',
        'regBenefitShare': 'Partagez des formulaires avec un seul lien',
        'regQuoteText': 'Passé de zéro à des formulaires entièrement fonctionnels en moins de 10 minutes.',
        'regQuoteAuthor': '\u2014 Sarah Chen, PM',
    },
    'de': {
        'illustrationTitle1': 'Weiter erstellen',
        'illustrationTitle2': 'tolle Formulare',
        'benefitAccess': 'Greifen Sie auf Formulare und Antworten zu',
        'benefitRules': 'Bedingte Regeln verwalten',
        'benefitAnalytics': 'Analysen und Einblicke ansehen',
        'benefitSecure': 'Sicherer, verschlüsselter Zugriff',
        'quoteText': 'Der beste Formular-Builder, den wir je benutzt haben.',
        'quoteAuthor': '\u2014 TechFlow Team',
        'regIllustrationTitle1': 'Beginnen Sie zu erstellen',
        'regIllustrationTitle2': 'dynamische Formulare noch heute',
        'regBenefitFree': 'Kostenloses Konto \u2014 keine Kreditkarte nötig',
        'regBenefitBuilder': 'Drag-and-Drop-Formular-Builder',
        'regBenefitLogic': 'Leistungsstarke bedingte Logik',
        'regBenefitShare': 'Formulare mit einem Link teilen',
        'regQuoteText': 'In weniger als 10 Minuten von null zu voll funktionsfähigen Formularen.',
        'regQuoteAuthor': '\u2014 Sarah Chen, PM',
    },
    'it': {
        'illustrationTitle1': 'Continua a creare',
        'illustrationTitle2': 'moduli straordinari',
        'benefitAccess': 'Accedi ai tuoi moduli e alle tue risposte',
        'benefitRules': 'Gestisci le regole condizionali',
        'benefitAnalytics': 'Visualizza analisi e approfondimenti',
        'benefitSecure': 'Accesso sicuro e crittografato',
        'quoteText': 'Il miglior creatore di moduli che abbiamo mai usato.',
        'quoteAuthor': '\u2014 Team TechFlow',
        'regIllustrationTitle1': 'Inizia a creare',
        'regIllustrationTitle2': 'moduli dinamici oggi',
        'regBenefitFree': 'Account gratuito \u2014 nessuna carta di credito',
        'regBenefitBuilder': 'Creatore di moduli drag-and-drop',
        'regBenefitLogic': 'Logica condizionale potente',
        'regBenefitShare': 'Condividi moduli con un solo link',
        'regQuoteText': 'Da zero a moduli completamente funzionali in meno di 10 minuti.',
        'regQuoteAuthor': '\u2014 Sarah Chen, PM',
    },
    'pt': {
        'illustrationTitle1': 'Continue criando',
        'illustrationTitle2': 'formulários incríveis',
        'benefitAccess': 'Acesse seus formulários e respostas',
        'benefitRules': 'Gerencie regras condicionais',
        'benefitAnalytics': 'Veja análises e insights',
        'benefitSecure': 'Acesso seguro e criptografado',
        'quoteText': 'O melhor criador de formulários que já usamos.',
        'quoteAuthor': '\u2014 Equipe TechFlow',
        'regIllustrationTitle1': 'Comece a criar',
        'regIllustrationTitle2': 'formulários dinâmicos hoje',
        'regBenefitFree': 'Conta gratuita \u2014 sem cartão de crédito',
        'regBenefitBuilder': 'Criador de formulários drag-and-drop',
        'regBenefitLogic': 'Lógica condicional poderosa',
        'regBenefitShare': 'Compartilhe formulários com um único link',
        'regQuoteText': 'Fomos de zero a formulários totalmente funcionais em menos de 10 minutos.',
        'regQuoteAuthor': '\u2014 Sarah Chen, PM',
    },
    'zh': {
        'illustrationTitle1': '继续创建',
        'illustrationTitle2': '出色的表单',
        'benefitAccess': '访问您的表单和回复',
        'benefitRules': '管理条件规则',
        'benefitAnalytics': '查看分析和见解',
        'benefitSecure': '安全、加密的访问',
        'quoteText': '我们用过的最好的表单生成器。',
        'quoteAuthor': '\u2014 TechFlow 团队',
        'regIllustrationTitle1': '开始创建',
        'regIllustrationTitle2': '今天就创建动态表单',
        'regBenefitFree': '免费账户 — 无需信用卡',
        'regBenefitBuilder': '拖放式表单生成器',
        'regBenefitLogic': '强大的条件逻辑',
        'regBenefitShare': '通过一个链接分享表单',
        'regQuoteText': '在不到10分钟内从零到功能完备的表单。',
        'regQuoteAuthor': '\u2014 陈莎拉，产品经理',
    },
    'ja': {
        'illustrationTitle1': '作成を続ける',
        'illustrationTitle2': '素晴らしいフォーム',
        'benefitAccess': 'フォームと回答にアクセス',
        'benefitRules': '条件ルールを管理',
        'benefitAnalytics': '分析とインサイトを表示',
        'benefitSecure': '安全で暗号化されたアクセス',
        'quoteText': 'これまで使った中で最高のフォームビルダーです。',
        'quoteAuthor': '\u2014 TechFlow チーム',
        'regIllustrationTitle1': '作成を始める',
        'regIllustrationTitle2': '今日からダイナミックなフォーム',
        'regBenefitFree': '無料アカウント \u2014 クレジットカード不要',
        'regBenefitBuilder': 'ドラッグ＆ドロップフォームビルダー',
        'regBenefitLogic': '強力な条件付きロジック',
        'regBenefitShare': '1つのリンクでフォームを共有',
        'regQuoteText': '10分以内にゼロから完全に機能するフォームへ。',
        'regQuoteAuthor': '\u2014 サラ・チェン、PM',
    },
    'ko': {
        'illustrationTitle1': '계속 만들기',
        'illustrationTitle2': '멋진 폼',
        'benefitAccess': '폼과 응답에 액세스',
        'benefitRules': '조건부 규칙 관리',
        'benefitAnalytics': '분석 및 인사이트 보기',
        'benefitSecure': '안전하고 암호화된 액세스',
        'quoteText': '우리가 사용해 본 최고의 폼 빌더입니다.',
        'quoteAuthor': '\u2014 TechFlow 팀',
        'regIllustrationTitle1': '만들기 시작',
        'regIllustrationTitle2': '오늘 바로 다이내믹 폼',
        'regBenefitFree': '무료 계정 — 신용카드 불필요',
        'regBenefitBuilder': '드래그 앤 드롭 폼 빌더',
        'regBenefitLogic': '강력한 조건부 로직',
        'regBenefitShare': '하나의 링크로 폼 공유',
        'regQuoteText': '10분도 안 되어 제로에서 완전한 기능의 폼까지.',
        'regQuoteAuthor': '\u2014 사라 첸, PM',
    },
    'ar': {
        'illustrationTitle1': 'واصل البناء',
        'illustrationTitle2': 'نماذج مذهلة',
        'benefitAccess': 'الوصول إلى نماذجك وردودك',
        'benefitRules': 'إدارة القواعد الشرطية',
        'benefitAnalytics': 'عرض التحليلات والرؤى',
        'benefitSecure': 'وصول آمن ومشفر',
        'quoteText': 'أفضل منشئ نماذج استخدمناه على الإطلاق.',
        'quoteAuthor': '\u2014 فريق TechFlow',
        'regIllustrationTitle1': 'ابدأ البناء',
        'regIllustrationTitle2': 'نماذج ديناميكية اليوم',
        'regBenefitFree': 'حساب مجاني — بدون بطاقة ائتمان',
        'regBenefitBuilder': 'منشئ نماذج بالسحب والإفلات',
        'regBenefitLogic': 'منطق شرطي قوي',
        'regBenefitShare': 'شارك النماذج برابط واحد',
        'regQuoteText': 'انتقلنا من الصفر إلى نماذج كاملة الوظائف في أقل من 10 دقائق.',
        'regQuoteAuthor': '\u2014 سارة تشين، مديرة المنتج',
    },
}

def main():
    for code, keys in AUTH_KEYS.items():
        path = os.path.join(BASE, code, 'translation.json')
        with open(path, encoding='utf-8') as f:
            data = json.load(f)
        auth = data.get('auth', {})
        # Insert keys preserving order (after strengthLabels if present)
        order = [
            'strengthLabels', 'fillFields', 'fixFields', 'passwordMatch', 'emailInvalid',
            'emailExists', 'usernameTaken', 'passwordWeak', 'noAccountFound',
            'incorrectPassword', 'accountDisabledMsg', 'notAuthenticated', 'sessionExpiredMsg',
            'illustrationTitle1', 'illustrationTitle2', 'benefitAccess', 'benefitRules',
            'benefitAnalytics', 'benefitSecure', 'quoteText', 'quoteAuthor',
            'regIllustrationTitle1', 'regIllustrationTitle2', 'regBenefitFree',
            'regBenefitBuilder', 'regBenefitLogic', 'regBenefitShare', 'regQuoteText',
            'regQuoteAuthor',
        ]
        merged = {k: auth[k] for k in order if k in auth}
        for k in auth:
            if k not in merged:
                merged[k] = auth[k]
        for k, v in keys.items():
            merged[k] = v
        data['auth'] = merged
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f'Updated {code}')

if __name__ == '__main__':
    main()
